config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  root to: 'posts#index'

    resources :posts do
        resources :comments
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    
    validates :title, presence: true,  #Ensure all posts will have a title that is at least 5 characters long
                      length: { minimum: 5 }  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
      @post = Post.find(params[:post_id])
      @comments = @post.comments
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @posts = Post.all
    end
    
    
    def show
        @post = Post.find(params[:id])   # To find the post we're searching for
    end
    
    
    def new
        @post = Post.new
    end
    
    
    def edit
        @post = Post.find(params[:id])
    end
    
    
    def create
        @post = Post.new(post_params)
        
       if @post.save
            redirect_to @post
       else
           render 'new'
       end
    end
    
    
    def update
         @post = Post.find(params[:id])
        
         if @post.update(post_params)
            redirect_to @post
         else
            render 'edit'
         end
    end
    
    
    def destroy
        
    end
    
    
    private
        def post_params
           params.require(:post).permit(:title, :body)    
        end
    
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/index.html.erb
<h1>Post <%= @post.title %> + Comments</h1>
<h4>An installment of cooking with Chef Dee</h4>

<p><%= @post.body %></p>

<hr>   
<h4>Comments<h4>
    
    <div class="comments-container">
       <% @comments.each do |c| %>
        <div class="comments">
            <p><strong><%= c.title %></strong></p>
            <p><%= c.body %></p>
        </div>
        
        <% end %>
        
    </div>
 
    <%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
    <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= form_with(model: @post, local: true) do %>

<% if @post.errors.any? %>
    <div id="error_explanation">
       <h2>
             <%= pluralize(@post.errors.count, "error") %> prohibited this article from being saved:
       </h2>
       <ul>
             <% @post.errors.full_messages.each do |msg| %>
                
             <li><%= msg %></li>
             <% end %>
       </ul>
    </div>
    <% end %>

<p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

<p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
</p>

<p>
    <%= form.submit %>
</p>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing all Awesome Posts</h1>


  <% @posts.each do |post| %>
    
       <div>
        <h3><%= post.title %></h3> 
        <p><%= truncate post.body, length: 150, separator: '' %></p> 
       </div> 

    <div>    
        <p><%= link_to 'Show Full Post', post_comments_path(post) %></p>
        <p><%= link_to 'Edit', edit_post_path(post) %></p>  
        <p><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p> 
    </div>

    <hr>
  <% end %>
    <br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with scope: :post, url: posts_path, local: true do |form| %>
 
<% if @post.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
        </h2>
        <ul>
            <% @post.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>


<p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
<strong>Title:</strong>
    <%= @post.title %>
</p>

<p>
<strong>Body:</strong>
    <%= @post.body %>
</p>

<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello, Welcome to my Blog!</h1>
<%=link_to 'MyBlogApp', controller: 'posts' %> 
<!-- <p>Find me in app/views/welcome/index.html.erb</p> -->